# Generated by Django 3.2.9 on 2021-12-08 01:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
